"""
Reliable CARLA RAG with Template-Based Generation
=================================================

This system uses proven code templates to ensure generated code always works.
"""

import os
import json
import time
from pathlib import Path
from dotenv import load_dotenv
import google.generativeai as genai

# Load environment variables
load_dotenv()

class TemplateBasedCarlaRAG:
    """RAG system using proven code templates."""
    
    def __init__(self, scenarios_db_path: str):
        """Initialize the system."""
        self.scenarios_db_path = scenarios_db_path
        
        # Configure Gemini API
        api_key = os.getenv("GOOGLE_API_KEY")
        if not api_key:
            raise ValueError("GOOGLE_API_KEY not found in .env file")
        
        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel('gemini-1.5-flash')
        
        # Load scenarios
        self.scenarios = self._load_scenarios()
        print(f"Loaded {len(self.scenarios)} scenarios")
        
        # Load the proven code template
        self.code_template = self._get_proven_template()
    
    def _load_scenarios(self):
        """Load scenarios from JSON file."""
        with open(self.scenarios_db_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        return data.get('scenarios', [])
    
    def _get_proven_template(self):
        """Get the proven working code template."""
        return '''#!/usr/bin/env python3
"""
CARLA Scenario: {scenario_description}
Generated by RAG Pipeline
========================

Configuration:
- Vehicles: {vehicle_count}
- Weather: {weather_type}
- Camera: {camera_mode}
- Duration: Configurable (default 30s)
"""

import carla
import time
import os
import argparse
import random
import sys

def main():
    """Main simulation function."""
    parser = argparse.ArgumentParser(description='{scenario_description}')
    parser.add_argument('--host', default='127.0.0.1', help='CARLA host')
    parser.add_argument('--port', type=int, default=2000, help='CARLA port')
    parser.add_argument('--duration', type=int, default=30, help='Simulation duration')
    parser.add_argument('--output', default='{output_dir}', help='Output directory')
    args = parser.parse_args()

    # Create output directory
    os.makedirs(args.output, exist_ok=True)
    print(f"Output directory: {{args.output}}")

    # Initialize variables
    vehicles = []
    camera = None
    frame_count = [0]
    
    print("Starting CARLA Scenario: {scenario_description}")
    print("=" * 60)
    
    try:
        # Connect to CARLA
        print(f"Connecting to CARLA at {{args.host}}:{{args.port}}...")
        client = carla.Client(args.host, args.port)
        client.set_timeout(10.0)
        
        # Test connection
        try:
            version = client.get_server_version()
            print(f"Connected to CARLA {{version}}")
        except Exception as e:
            print(f"Failed to connect: {{e}}")
            print("Make sure CARLA server is running on localhost:2000")
            return 1
        
        # Get world and blueprints
        world = client.get_world()
        blueprint_library = world.get_blueprint_library()
        print(f"Current map: {{world.get_map().name}}")
        
        # Setup weather
        print("Setting up {weather_type} weather...")
        {weather_setup}
        world.set_weather(weather)
        print("Weather applied successfully")
        
        # Get vehicle blueprints
        vehicle_bps = blueprint_library.filter('vehicle.*')
        vehicle_bps = [x for x in vehicle_bps if int(x.get_attribute('number_of_wheels')) == 4]
        
        # Get spawn points
        spawn_points = world.get_map().get_spawn_points()
        if len(spawn_points) < {vehicle_count}:
            print(f"Warning: Only {{len(spawn_points)}} spawn points available")
        
        # Spawn vehicles
        print("Spawning {vehicle_count} vehicles...")
        for i in range({vehicle_count}):
            attempts = 0
            vehicle = None
            
            while vehicle is None and attempts < 10:
                try:
                    vehicle_bp = random.choice(vehicle_bps)
                    spawn_point = spawn_points[(i + attempts) % len(spawn_points)]
                    vehicle = world.try_spawn_actor(vehicle_bp, spawn_point)
                    
                    if vehicle is not None:
                        vehicle.set_autopilot(True)
                        vehicles.append(vehicle)
                        print(f"  Vehicle {{i+1}} spawned: {{vehicle_bp.id}}")
                        break
                    else:
                        attempts += 1
                except Exception as e:
                    attempts += 1
                    if attempts >= 10:
                        print(f"  Failed to spawn vehicle {{i+1}}")
        
        if not vehicles:
            print("Failed to spawn any vehicles")
            return 1
        
        print(f"Successfully spawned {{len(vehicles)}} vehicles")
        
        # Setup camera
        print("Setting up {camera_mode} camera...")
        camera_bp = blueprint_library.find('sensor.camera.rgb')
        camera_bp.set_attribute('image_size_x', '1280')
        camera_bp.set_attribute('image_size_y', '720')
        camera_bp.set_attribute('fov', '110')
        camera_bp.set_attribute('sensor_tick', '0.033')
        
        # Camera positioning
        {camera_transform}
        
        # Spawn camera
        camera = world.spawn_actor(camera_bp, camera_transform, attach_to=vehicles[0])
        print("Camera attached successfully")
        
        # Setup frame saving
        def save_frame(image):
            try:
                filename = f"frame_{{frame_count[0]:06d}}.png"
                filepath = os.path.join(args.output, filename)
                image.save_to_disk(filepath)
                frame_count[0] += 1
                
                if frame_count[0] % 30 == 0:
                    print(f"  Saved {{frame_count[0]}} frames...")
            except Exception as e:
                print(f"Error saving frame: {{e}}")
        
        camera.listen(save_frame)
        print("Frame recording started")
        
        # Run simulation
        print(f"Running simulation for {{args.duration}} seconds...")
        print("Press Ctrl+C to stop early")
        
        start_time = time.time()
        try:
            while time.time() - start_time < args.duration:
                world.tick()
                time.sleep(0.05)
        except KeyboardInterrupt:
            print("\\nStopped by user")
        
        elapsed = time.time() - start_time
        print(f"\\nSimulation completed after {{elapsed:.1f}} seconds")
        print(f"Total frames saved: {{frame_count[0]}}")
        print(f"Frames saved to: {{os.path.abspath(args.output)}}")
        
    except Exception as e:
        print(f"Error during simulation: {{e}}")
        import traceback
        traceback.print_exc()
        return 1
        
    finally:
        print("\\nCleaning up...")
        
        # Stop camera
        if camera is not None:
            try:
                camera.stop()
                print("Camera stopped")
            except:
                pass
        
        # Destroy vehicles
        destroyed = 0
        for vehicle in vehicles:
            if vehicle is not None:
                try:
                    vehicle.destroy()
                    destroyed += 1
                except:
                    pass
        
        if destroyed > 0:
            print(f"Destroyed {{destroyed}} vehicles")
        
        # Destroy camera
        if camera is not None:
            try:
                camera.destroy()
                print("Camera destroyed")
            except:
                pass
        
        print("Cleanup complete")
    
    return 0

if __name__ == '__main__':
    try:
        exit_code = main()
        sys.exit(exit_code)
    except KeyboardInterrupt:
        print("\\nInterrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\\nFatal error: {{e}}")
        sys.exit(1)
'''
    
    def find_best_match(self, user_input: str):
        """Find the best matching scenario."""
        scenario_texts = []
        for i, scenario in enumerate(self.scenarios):
            text = f"Scenario {i}: {scenario['description']} - Keywords: {', '.join(scenario['keywords'])}"
            scenario_texts.append(text)
        
        prompt = f"""
        User request: "{user_input}"
        
        Available scenarios:
        {chr(10).join(scenario_texts)}
        
        Return only the number (0, 1, 2, etc.) of the best matching scenario.
        """
        
        try:
            response = self.model.generate_content(prompt)
            scenario_index = int(response.text.strip())
            return self.scenarios[scenario_index]
        except:
            return self.scenarios[0]
    
    def generate_code_from_template(self, user_input: str, scenario: dict):
        """Generate code using the proven template."""
        
        # Extract parameters
        params = scenario['parameters']
        weather_type = params.get('weather', 'clear')
        vehicle_count = params.get('vehicle_count', 1)
        camera_mode = params.get('camera_mode', 'follow_car')
        
        # Weather setup code
        weather_setups = {
            'rain': '''weather = carla.WeatherParameters(
            cloudiness=90.0, precipitation=80.0, precipitation_deposits=85.0,
            wind_intensity=30.0, sun_altitude_angle=45.0, fog_density=10.0,
            fog_distance=50.0, wetness=80.0
        )''',
            'snow': '''weather = carla.WeatherParameters(
            cloudiness=95.0, precipitation=60.0, precipitation_deposits=90.0,
            wind_intensity=20.0, sun_altitude_angle=30.0, fog_density=20.0,
            fog_distance=30.0, wetness=10.0
        )''',
            'fog': '''weather = carla.WeatherParameters(
            cloudiness=80.0, precipitation=0.0, precipitation_deposits=0.0,
            wind_intensity=10.0, sun_altitude_angle=45.0, fog_density=70.0,
            fog_distance=20.0, wetness=0.0
        )''',
            'night': '''weather = carla.WeatherParameters(
            cloudiness=20.0, precipitation=0.0, precipitation_deposits=0.0,
            wind_intensity=5.0, sun_altitude_angle=-30.0, fog_density=0.0,
            fog_distance=100.0, wetness=0.0
        )''',
            'clear': '''weather = carla.WeatherParameters(
            cloudiness=10.0, precipitation=0.0, precipitation_deposits=0.0,
            wind_intensity=10.0, sun_altitude_angle=70.0, fog_density=0.0,
            fog_distance=100.0, wetness=0.0
        )'''
        }
        
        # Camera transform code
        camera_transforms = {
            'follow_car': 'camera_transform = carla.Transform(carla.Location(x=-6.0, z=3.5), carla.Rotation(pitch=-10))',
            'third_person': 'camera_transform = carla.Transform(carla.Location(x=-6.0, z=3.5), carla.Rotation(pitch=-10))',
            'overhead': 'camera_transform = carla.Transform(carla.Location(x=0.0, z=15.0), carla.Rotation(pitch=-90))',
            'first_person': 'camera_transform = carla.Transform(carla.Location(x=1.5, z=1.4), carla.Rotation(pitch=0))',
            'intersection': 'camera_transform = carla.Transform(carla.Location(x=0.0, z=15.0), carla.Rotation(pitch=-90))'
        }
        
        # Generate output directory name
        safe_scenario_name = scenario['id'].replace('_', '-')
        output_dir = f"{safe_scenario_name}-frames"
        
        # Fill in the template
        code = self.code_template.format(
            scenario_description=scenario['description'],
            vehicle_count=vehicle_count,
            weather_type=weather_type,
            camera_mode=camera_mode,
            output_dir=output_dir,
            weather_setup=weather_setups.get(weather_type, weather_setups['clear']),
            camera_transform=camera_transforms.get(camera_mode, camera_transforms['follow_car'])
        )
        
        return code
    
    def save_generated_code(self, code: str, scenario: dict, user_input: str):
        """Save the generated code."""
        timestamp = int(time.time())
        safe_name = scenario['id'].replace('_', '-')
        filename = f"reliable_{safe_name}_{timestamp}.py"
        filepath = os.path.join("../generated_scenarios", filename)
        
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        
        try:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(code)
            print(f"Code saved to: {filepath}")
            return filepath
        except Exception as e:
            print(f"Error saving code: {e}")
            return None
    
    def process_request(self, user_input: str):
        """Process request and generate reliable code."""
        
        print(f"Processing: '{user_input}'")
        print("-" * 50)
        
        try:
            # Find best scenario
            print("Finding best scenario match...")
            scenario = self.find_best_match(user_input)
            print(f"Selected: {scenario['description']}")
            
            # Generate code using template
            print("Generating reliable CARLA code...")
            code = self.generate_code_from_template(user_input, scenario)
            
            # Validate syntax
            print("Validating code syntax...")
            try:
                compile(code, '<template_code>', 'exec')
                print("Syntax validation: PASSED")
                syntax_ok = True
            except SyntaxError as e:
                print(f"Syntax validation: FAILED - {e}")
                syntax_ok = False
                return {'success': False, 'error': f"Syntax error: {e}"}
            
            # Save code
            print("Saving generated code...")
            filepath = self.save_generated_code(code, scenario, user_input)
            
            if not filepath:
                return {'success': False, 'error': "Failed to save code"}
            
            # Create explanation
            explanation = f"""
RAG Pipeline Results:
===================

Request: "{user_input}"
Scenario: {scenario['description']}
Configuration:
- Vehicles: {scenario['parameters']['vehicle_count']}
- Weather: {scenario['parameters']['weather']}
- Camera: {scenario['parameters']['camera_mode']}

Generated file: {filepath}

The code is ready to run with:
python {os.path.basename(filepath)} --duration 30

This will create frames in the output directory for dataset creation.
            """
            
            print(explanation)
            
            return {
                'success': True,
                'code': code,
                'filepath': filepath,
                'scenario': scenario,
                'explanation': explanation,
                'user_input': user_input
            }
            
        except Exception as e:
            print(f"Error: {e}")
            return {'success': False, 'error': str(e)}

def main():
    """Main function."""
    
    print("Reliable CARLA RAG with Template-Based Generation")
    print("=" * 60)
    
    try:
        # Initialize system
        rag = TemplateBasedCarlaRAG("../carla_scenarios_db.json")
        
        # Example requests
        examples = [
            "2 cars driving in rainy weather and camera following from third person view",
            "Multiple vehicles at intersection with overhead camera",
            "Night driving with 3 vehicles and headlights",
            "Single car in sunny weather"
        ]
        
        print("\\nExample requests:")
        for i, ex in enumerate(examples, 1):
            print(f"{i}. {ex}")
        
        while True:
            print("\\n" + "="*60)
            choice = input("\\nEnter request number (1-4), custom text, or 'quit': ").strip()
            
            if choice.lower() in ['quit', 'exit', 'q']:
                break
            
            # Get user input
            if choice.isdigit() and 1 <= int(choice) <= len(examples):
                user_input = examples[int(choice) - 1]
            else:
                user_input = choice
            
            if not user_input:
                continue
            
            # Process request
            result = rag.process_request(user_input)
            
            if result['success']:
                print("\\nSUCCESS: Reliable code generated!")
                print(f"File: {result['filepath']}")
                print("\\nTo run the scenario:")
                print(f"1. Make sure CARLA server is running")
                print(f"2. cd generated_scenarios")
                print(f"3. python {os.path.basename(result['filepath'])} --duration 30")
            else:
                print(f"\\nFAILED: {result['error']}")
    
    except Exception as e:
        print(f"System error: {e}")

if __name__ == "__main__":
    main()
